# Generated by Django 4.2.17 on 2026-03-27 15:18

from django.db import migrations


def backfill_onboarding_completed(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    # Mark users who have dietary preferences or allergies filled in
    User.objects.exclude(dietary_preferences=[]).update(onboarding_completed=True)
    User.objects.exclude(allergies=[]).update(onboarding_completed=True)
    # Mark users who own restaurants
    from django.db.models import Exists, OuterRef
    Restaurant = apps.get_model("restaurants", "Restaurant")
    User.objects.filter(
        Exists(Restaurant.objects.filter(owner=OuterRef("pk")))
    ).update(onboarding_completed=True)


def reverse(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.update(onboarding_completed=False)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_onboarding_completed_user_onboarding_dismissed"),
        ("restaurants", "0011_remove_restaurant_address"),
    ]

    operations = [
        migrations.RunPython(backfill_onboarding_completed, reverse),
    ]
