# Generated by Django 4.2.28 on 2026-03-26 15:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_account_id', models.CharField(max_length=255, unique=True)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('charges_enabled', models.BooleanField(default=False)),
                ('pending_refund_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connected_account', to='restaurants.restaurant')),
            ],
        ),
    ]
