# Generated by Django 4.2.17 on 2026-02-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0003_menucategory_menuitem_menuitemvariant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="currency",
            field=models.CharField(default="USD", help_text="ISO 4217 currency code", max_length=3),
        ),
    ]
