# Generated by Django 4.2.17 on 2026-02-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0004_add_currency_to_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="homepage",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="logo_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
