# Generated by Django 4.2.17 on 2026-02-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0005_add_restaurant_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Tax rate as a percentage (e.g. 8.875 for 8.875%)",
                max_digits=5,
            ),
        ),
    ]
