# Generated by Django 4.2.17 on 2026-03-27 15:06

from django.db import migrations


def copy_address_to_street_address(apps, schema_editor):
    """Copy old address field to street_address for existing records."""
    from django.db.models import F

    Restaurant = apps.get_model("restaurants", "Restaurant")
    Restaurant.objects.exclude(address="").update(street_address=F("address"))


def reverse_copy(apps, schema_editor):
    """Copy street_address back to address for rollback."""
    from django.db.models import F

    Restaurant = apps.get_model("restaurants", "Restaurant")
    Restaurant.objects.exclude(street_address="").update(address=F("street_address"))


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0009_restaurant_city_restaurant_country_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_address_to_street_address, reverse_copy),
    ]
