# Generated by Django 4.2.17 on 2026-03-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_copy_address_to_street_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
    ]
