# Generated by Django 4.2.29 on 2026-04-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_remove_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_upsellable',
            field=models.BooleanField(default=False),
        ),
    ]
