# Generated by Django 4.2.29 on 2026-04-04 22:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_widen_lat_lng_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name, e.g. 'Patio 3'", max_length=50)),
                ('number', models.CharField(help_text="Short identifier used in QR URL, e.g. 'A1'", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('restaurant', 'number')},
            },
        ),
    ]
