# Generated by Django 4.2.29 on 2026-04-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_add_table_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuversion',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai_upload', 'AI Upload'), ('toast_sync', 'Toast Sync')], default='manual', max_length=20),
        ),
    ]
