# Generated by Django 4.2.17 on 2026-04-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_add_toast_sync_menu_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='payment_model',
            field=models.CharField(choices=[('upfront', 'Pay Upfront'), ('tab', 'Open Tab')], default='upfront', max_length=20),
        ),
    ]
