# Generated by Django 4.2.17 on 2026-04-11 20:30

from django.db import migrations, models


def migrate_is_active_to_status(apps, schema_editor):
    MenuItem = apps.get_model("restaurants", "MenuItem")
    MenuItem.objects.filter(is_active=False).update(status="inactive")


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_add_payment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='status',
            field=models.CharField(
                choices=[('active', 'Active'), ('sold_out', 'Sold out'), ('inactive', 'Inactive')],
                default='active',
                max_length=10,
            ),
        ),
        migrations.RunPython(migrate_is_active_to_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_active',
        ),
    ]
