# Generated by Django 4.2.17 on 2026-04-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_menu_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
