# Generated by Django 4.2.28 on 2026-03-26 15:25

from django.db import migrations, models
import django.db.models.deletion


def set_existing_orders_transferred(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.all().update(payout_status="transferred")


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_payout'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurants.payout'),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('transferred', 'Transferred'), ('paid_out', 'Paid Out'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.RunPython(set_existing_orders_transferred, migrations.RunPython.noop),
    ]
