# Generated by Django 4.2.17 on 2026-03-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paid_at_order_payout_order_payout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_order_id',
            field=models.CharField(blank=True, help_text='Order ID in external POS system', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pos_sync_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('synced', 'Synced'), ('retrying', 'Retrying'), ('failed', 'Failed'), ('manually_resolved', 'Manually Resolved')], default='not_applicable', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('pos_collected', 'POS Collected'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
