# Generated by Django 4.2.17 on 2026-02-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_add_payment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_payment_method_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
