# Generated by Django 4.2.17 on 2026-02-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_stripe_payment_method_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_allergies",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Snapshot of customer allergies at time of order",
            ),
        ),
    ]
