# Generated by Django 4.2.17 on 2026-04-09 03:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_add_payment_model'),
        ('orders', '0006_order_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_identifier', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closing', 'Closing'), ('closed', 'Closed')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='restaurants.restaurant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tab',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('restaurant', 'table_identifier'), name='unique_open_tab_per_table'),
        ),
    ]
