# Generated by Django 4.2.17 on 2026-04-09 03:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_order_tab_fk_and_deferred'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('full', 'Full'), ('split_even', 'Split Even'), ('pay_by_item', 'Pay By Item')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('split_count', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(blank=True, related_name='tab_payments', to='orders.orderitem')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.tab')),
            ],
        ),
    ]
