# Generated by Django 4.2.17 on 2026-03-26 20:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_paid_at_order_payout_order_payout_status'),
        ('restaurants', '0003_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pos_type', models.CharField(choices=[('square', 'Square'), ('toast', 'Toast'), ('middleware', 'Middleware'), ('none', 'None')], default='none', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_mode', models.CharField(choices=[('stripe', 'Stripe'), ('pos_collected', 'POS Collected')], default='stripe', max_length=20)),
                ('oauth_access_token', models.TextField(blank=True, default='')),
                ('oauth_refresh_token', models.TextField(blank=True, default='')),
                ('oauth_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('external_location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('middleware_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_connection', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='POSSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('manually_resolved', 'Manually Resolved')], default='pending', max_length=20)),
                ('external_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_sync_logs', to='orders.order')),
                ('pos_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.posconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
